
#' The here() function always returns a full path from the root directory
#' This function returns a path from the project root for less clutter
#' and greater portability
#' 
#' @param path String, full path as generated by here::here("blah")
path_from_here <- function(path) {
    
    paste0(basename(here::here()), # Project root directory
           strsplit(path, basename(here::here()))[[1]][2]) # Chosen path relative to project root
    
}

rr_save <- function() {
    
    
}

rr_write_tsv <- function(df, path, desc, verbose = TRUE) {
    
    # Need readr to simplify table writing
    require(readr)
    readr::write_tsv(df, path)
    
    # Create the path for the description file, swapping .tsv extension to .desc
    desc_path <- gsub("tsv$", "desc", path)
    
    # Print the object description to the desc file
    cat(desc, file = desc_path, sep = "\n")
    
    # Output a message with path to desc file
    if (verbose) message("...writing description of ", basename(path), " to ", path_from_here(desc_path))
    
}

rr_ggplot <- function(df, plot_num, ...) {
    
    require(ggplot2)
    require(readr)
    
    # TODO: Currently, it's not possible to not specify plot_num, because
    # it messes up the dots (...) which are passed to ggplot, so this if statement
    # is never evaluated, an error is thrown instead:

    # If the plot # is not provided
    if (missing(plot_num)) {
        
        plot_num <- 1
        # This is beacuse plots are named by their number in each chunk, but
        # that number cannot be accessed by this function
        warning("!! If more than one ggplot is generated in this chunk with rr_ggplot(),",
                "only the source data for the first one will be saved.",
                "Pass plot # explicitly to plot_num argument to correct this.")
        
    }
    
    # Get the figure path for the current chunk, without file extensions
    # https://github.com/yihui/knitr/issues/73#issuecomment-3514096
    fig_path <- knitr::fig_path(number = plot_num)
    
    # Make a path for the source data by appending a suffix to the figure path,
    # and write source data there as a TSV
    src_path <- paste0(fig_path, ".source_data.tsv")
    write_tsv(df, src_path)
    
    # Output a message with path to source data file
    message("...writing source data of ggplot to ", path_from_here(src_path))

    # Proceed with ggplot
    ggplot(data = df, ...)
    
}

rr_load <- function() {
    
    
}

#' @param path String, as returned by here::here("blah")
rr_read_tsv <- function(path, ...) {
    
    require(readr)
    require(stringr)
    
    # Create the path for the description file, swapping .tsv extension to .desc
    desc_path <- gsub("tsv$", "desc", path)
    
    # Get the number of the analysis, e.g. "01"
    doc_idx <- stringr::str_extract(path, "(\\d)+")
    
    # Search analysis folder for .Rmd file matching doc_idx
    script <- list.files(here("analysis"), pattern = glob2rx(paste0(doc_idx, "*.Rmd")))
    
    # Get the timestamp for when the file contents were last modified
    timestamp <- file.info(path)$mtime
    
    # We use cat here because it returns to stdout, which will be picked
    # up by the code folding js script (hideOutput.js). Otherwise, there will
    # be one folding button per line of output
    # https://stackoverflow.com/questions/36699272/why-is-message-a-better-choice-than-print-in-r-for-writing-a-package
    cat(paste0(path_from_here(path), " info:\n",
            "...description : ",   readLines(desc_path),
            "\n...generated by: ", path_from_here(here("analysis", script)),
            "\n...last updated: ", timestamp))
    # e.g. output
    # /Users/selinjessa/Repos/rr/output/01/mtcars.tsv info:
    # ...description : The mtcars dataset, verbatim
    # ...generated by: rr/analysis/01-first_step.Rmd
    # ...last updated: 2020-05-23 22:31:53
    
    # Read the file and return as dataframe
    suppressMessages(readr::read_tsv(path, ...))
    
}
